#!/bin/bash
## SparkyBonsai JWM Menu Maker bash script v 2.2
## Enhanced with MX Tools category support
## published under GPLv2
## author mauros (enhanced for MX Tools support)
## for SparkyBonsai GNU/Linux https://github.com/maurosh/SparkyBonsai
## Usage: save and chmod +x or register this script on your system and put into .jwmrc file
## the xml tag: "<Include>exec: menumaker</Include>"

## modules icon
icomod="user-bookmarks";

## modules name
namemod="DDog Tools";

## MX Tools configuration
if [[ -f "/usr/share/pixmaps/mx.png" ]]; then
    mxtools_icon="/usr/share/pixmaps/mx.png";
elif [[ -f "/usr/share/pixmaps/othertools.png" ]]; then
    mxtools_icon="/usr/share/pixmaps/othertools.png";
else
    mxtools_icon="applications-system";
fi
mxtools_name="MX Tools";

## localization
lc="${LANG%_*}";

## Creating apps array
IFS=$'\n';
apparray=($(find /usr/share/applications/ -maxdepth 1 -name "*.desktop"));

## Fixing array and identifying MX tools
mxtools_array=()
for i in "${!apparray[@]}"; do
    NoDisplay=$(grep '^NoDisplay' ${apparray[$i]} | sed 's/^NoDisplay=//')
    Terminal=$(grep '^Terminal' ${apparray[$i]} | sed 's/^Terminal=//')
    
    # Check if this is an MX tool by filename
    filename=$(basename "${apparray[$i]}")
    if [[ "$filename" == *"mx"* || "$filename" == *"MX"* || "$filename" == *"Mx"* ]]; then
        mxtools_array+=("${apparray[$i]}")
    fi
    
    if [[ "$NoDisplay" = "true" || "$Terminal" = "true" ]]; then
        unset -v 'apparray[$i]';
    fi
done

# Sort MX tools array by filename
if [ ${#mxtools_array[@]} -gt 0 ]; then
    IFS=$'\n' mxtools_sorted=($(sort <<<"${mxtools_array[*]}"))
    mxtools_array=("${mxtools_sorted[@]}")
    unset mxtools_sorted
fi

IFS=$'\n' appsorted=($(sort <<<"${apparray[*]}"))
apparray=("${appsorted[@]}");
unset appsorted;
unset IFS;

## Function to check if app is MX tool
is_mx_tool() {
    local app_path="$1"
    local filename=$(basename "$app_path")
    if [[ "$filename" == *"mx"* || "$filename" == *"MX"* || "$filename" == *"Mx"* ]]; then
        return 0  # true
    else
        return 1  # false
    fi
}

## Creating categories array
IFS=$'\n';
apparraylc=($(find /usr/share/desktop-directories -maxdepth 1 -name "*.directory"));

## Getting categories data
catarraylc=(hoo);
icoarraylc=();
for i in "${!apparraylc[@]}"; do
   namarraylc="$(grep '^Name=' ${apparraylc[$i]} | head -1 | sed 's/^Name=//' | tail -1)";
   devnamelc="$(grep 'Name\['$lc'\]=' ${apparraylc[$i]})";
   devnamelc="${devnamelc##*=}";
   icolc=( "$(grep '^Icon=' ${apparraylc[$i]} | sed 's/^Icon=//' | head -1)" );
   if [[ -z "$devnamelc" ]]; then
      devnamelc="$namarraylc";
   fi
   if [[ "$namarraylc" == *"Accessories"* ]]; then
      catarraylc[1]="$devnamelc";
      icoarraylc[1]="$icolc";
   fi
   if [[ "$namarraylc" == *"Education"* ]]; then
      catarraylc[2]="$devnamelc";
      icoarraylc[2]="$icolc";
   fi
   if [[ "$namarraylc" == *"Game"* ]]; then
      catarraylc[3]="$devnamelc";
      icoarraylc[3]="$icolc";
   fi
   if [[ "$namarraylc" == *"Graphics"* ]]; then
      catarraylc[4]="$devnamelc";
      icoarraylc[4]="$icolc";
   fi
   if [[ "$namarraylc" == *"Internet"* ]]; then
      catarraylc[5]="$devnamelc";
      icoarraylc[5]="$icolc";
   fi
   if [[ "$namarraylc" == *"Office"* ]]; then
      catarraylc[6]="$devnamelc";
      icoarraylc[6]="$icolc";
   fi
   if [[ "$namarraylc" == *"Other"* ]]; then
      catarraylc[7]="$devnamelc";
      icoarraylc[7]="$icolc";
   fi
   if [[ "$namarraylc" == *"Development"* || "$namarraylc" == *"Programming"* ]]; then 
      catarraylc[8]="$devnamelc";
      icoarraylc[8]="$icolc";
   fi
   if [[ "$namarraylc" == *"Audio"* || "$namarraylc" == *"Video"* || "$namarraylc" == *"Player"* ]]; then
      catarraylc[9]="$devnamelc";
      icoarraylc[9]="$icolc";
   fi
   if [[ "$namarraylc" == *"System"* ]]; then
      catarraylc[10]="$devnamelc";
      icoarraylc[10]="$icolc";
   fi
   if [[ "$namarraylc" == *"Preferences"* ]]; then
      catarraylc[11]="$devnamelc";
      icoarraylc[11]="$icolc";
   fi
   if [[ "$namarraylc" == *"Science"* ]]; then
      catarraylc[12]="$devnamelc";
      icoarraylc[12]="$icolc";
   fi
   if [[ "$namarraylc" == *"Universal"* ]]; then
      catarraylc[13]="$devnamelc";
      icoarraylc[13]="$icolc";
   fi
done

## Getting apps data
catarray=();
namarray=();
icoarray=();
exearray=();
for i in "${!apparray[@]}"; do
      catarray+=( "$(grep '^Categories' ${apparray[$i]} | sed 's/^Categories=//')" );
      devname="$(grep 'Name\['$lc'\]=' ${apparray[$i]})";
      devname="${devname##*=}";
      if [[ -z "$devname" ]]; then
         namarray+=( "$(grep '^Name=' ${apparray[$i]} | head -1 | sed 's/^Name=//' | tail -1)" );
      else
         namarray+=( "$devname" );
      fi

      icoarray+=( "$(grep '^Icon=' ${apparray[$i]} | sed 's/^Icon=//' | head -1)" );
      exearray+=( "$(grep '^Exec' ${apparray[$i]} | head -1 | sed 's/^Exec=//' | tail -1 | sed 's/%.//')" );
done

## Categories detection
cmx="no"  # MX Tools category flag
for i in "${!apparray[@]}"; do
      # Check if this app is an MX tool
      if is_mx_tool "${apparray[$i]}"; then
          cmx="yes"
          continue  # Skip other category checks for MX tools
      fi
      
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"Utility"* && "$Categories" != *"System"* && "$Categories" != *"Modul"* ]]; then
         cacc="yes";
      fi
      if [[ "$Categories" == *"Education"* ]]; then
         cedu="yes";
      fi
      if [[ "$Categories" == *"Game"* ]]; then
         cgam="yes";
      fi
      if [[ "$Categories" == *"Graphics"* ]]; then
         cgra="yes";
      fi
      if [[ "$Categories" == *"Network"* ]]; then
         cnet="yes";
      fi
      if [[ "$Categories" == *"Office"* ]]; then
         coff="yes";
      fi
      if [[ "$Categories" == *"Other"* ]]; then
         coth="yes";
      fi
      if [[ "$Categories" == *"Development"* || "$Categories" == *"Programming"* ]]; then
         cdev="yes";
      fi
      if [[ "$Categories" == *"Audio"* || "$Categories" == *"Video"* || "$Categories" == *"Player"* ]]; then
         caud="yes";
      fi
      if [[ "$Categories" == *"System"* || "$Categories" == *"Settings"* && "$Categories" != *"Modul"* ]]; then
         csys="yes";
      fi
      if [[ "$Categories" == *"Preferences"* && "$Categories" != *"System"* ]]; then
         cpre="yes";
      fi
      if [[ "$Categories" == *"Modul"* ]]; then
         cmod="yes";
      fi
      if [[ "$Categories" == *"Universal"*  && "$Categories" != *"System"* ]]; then
         cuni="yes";
      fi
      if [[ "$Categories" == *"Science"*  && "$Categories" != *"System"* ]]; then
         csci="yes";
      fi
done

## XML header
echo '<?xml version="1.0"?>';
echo '<JWM>';

## MX Tools Menu (placed first for prominence)
if [[ "$cmx" = "yes" && ${#mxtools_array[@]} -gt 0 ]]; then
    echo '<Menu label="'$mxtools_name'" icon="'$mxtools_icon'">';
    
    # Get MX tools data
    for mx_app in "${mxtools_array[@]}"; do
        mx_devname="$(grep 'Name\['$lc'\]=' $mx_app)";
        mx_devname="${mx_devname##*=}";
        if [[ -z "$mx_devname" ]]; then
            mx_devname="$(grep '^Name=' $mx_app | head -1 | sed 's/^Name=//' | tail -1)";
        fi
        
        mx_icon="$(grep '^Icon=' $mx_app | sed 's/^Icon=//' | head -1)";
        mx_exec="$(grep '^Exec' $mx_app | head -1 | sed 's/^Exec=//' | tail -1 | sed 's/%.//')";
        
        echo '<Program label="'$mx_devname'" icon="'$mx_icon'">'$mx_exec'</Program>';
    done
    
    echo '</Menu>';
fi

## Accessories Menu
if [[ "$cacc" = "yes" ]]; then
echo '<Menu label="'${catarraylc[1]}'" icon="'${icoarraylc[1]}'">';
for i in "${!apparray[@]}"; do
      # Skip MX tools
      if is_mx_tool "${apparray[$i]}"; then
          continue
      fi
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"Utility"* && "$Categories" != *"System"* && "$Categories" != *"Modul"* ]]; then
         echo '<Program label="'${namarray[$i]}'" icon="'${icoarray[$i]}'">'${exearray[$i]}'</Program>'; 
      fi
done
echo '</Menu>';
fi

## Education Menu
if [[ "$cedu" = "yes" ]]; then
echo '<Menu label="'${catarraylc[2]}'" icon="'${icoarraylc[2]}'">';
for i in "${!apparray[@]}"; do
      # Skip MX tools
      if is_mx_tool "${apparray[$i]}"; then
          continue
      fi
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"Education"* ]]; then
         echo '<Program label="'${namarray[$i]}'" icon="'${icoarray[$i]}'">'${exearray[$i]}'</Program>'; 
      fi
done
echo '</Menu>';
fi

## Games Menu
if [[ "$cgam" = "yes" ]]; then
echo '<Menu label="'${catarraylc[3]}'" icon="'${icoarraylc[3]}'">';
for i in "${!apparray[@]}"; do
      # Skip MX tools
      if is_mx_tool "${apparray[$i]}"; then
          continue
      fi
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"Game"* ]]; then
         echo '<Program label="'${namarray[$i]}'" icon="'${icoarray[$i]}'">'${exearray[$i]}'</Program>'; 
      fi
done
echo '</Menu>';
fi

## Graphics Menu
if [[ "$cgra" = "yes" ]]; then
echo '<Menu label="'${catarraylc[4]}'" icon="'${icoarraylc[4]}'">';
for i in "${!apparray[@]}"; do
      # Skip MX tools
      if is_mx_tool "${apparray[$i]}"; then
          continue
      fi
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"Graphics"* ]]; then
         echo '<Program label="'${namarray[$i]}'" icon="'${icoarray[$i]}'">'${exearray[$i]}'</Program>'; 
      fi
done
echo '</Menu>';
fi

## Network Menu
if [[ "$cnet" = "yes" ]]; then
echo '<Menu label="'${catarraylc[5]}'" icon="'${icoarraylc[5]}'">';
for i in "${!apparray[@]}"; do
      # Skip MX tools
      if is_mx_tool "${apparray[$i]}"; then
          continue
      fi
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"Network"* ]]; then
         echo '<Program label="'${namarray[$i]}'" icon="'${icoarray[$i]}'">'${exearray[$i]}'</Program>'; 
      fi
done
echo '</Menu>';
fi

## Office Menu
if [[ "$coff" = "yes" ]]; then
echo '<Menu label="'${catarraylc[6]}'" icon="'${icoarraylc[6]}'">';
for i in "${!apparray[@]}"; do
      # Skip MX tools
      if is_mx_tool "${apparray[$i]}"; then
          continue
      fi
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"ffice"* ]]; then
         echo '<Program label="'${namarray[$i]}'" icon="'${icoarray[$i]}'">'${exearray[$i]}'</Program>'; 
      fi
done
echo '</Menu>';
fi

## Other Menu
if [[ "$coth" = "yes" ]]; then
echo '<Menu label="'${catarraylc[7]}'" icon="'${icoarraylc[7]}'">';
for i in "${!apparray[@]}"; do
      # Skip MX tools
      if is_mx_tool "${apparray[$i]}"; then
          continue
      fi
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"Other"* ]]; then
         echo '<Program label="'${namarray[$i]}'" icon="'${icoarray[$i]}'">'${exearray[$i]}'</Program>'; 
      fi
done
echo '</Menu>';
fi

## Development Menu
if [[ "$cdev" = "yes" ]]; then
echo '<Menu label="'${catarraylc[8]}'" icon="'${icoarraylc[8]}'">';
for i in "${!apparray[@]}"; do
      # Skip MX tools
      if is_mx_tool "${apparray[$i]}"; then
          continue
      fi
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"Development"* ]]; then
         echo '<Program label="'${namarray[$i]}'" icon="'${icoarray[$i]}'">'${exearray[$i]}'</Program>'; 
      fi
done
echo '</Menu>';
fi

## AudioVideo Menu
if [[ "$caud" = "yes" ]]; then
echo '<Menu label="'${catarraylc[9]}'" icon="'${icoarraylc[9]}'">';
for i in "${!apparray[@]}"; do
      # Skip MX tools
      if is_mx_tool "${apparray[$i]}"; then
          continue
      fi
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"Audio"* || "$Categories" == *"Video"* || "$Categories" == *"Player"* ]]; then
         echo '<Program label="'${namarray[$i]}'" icon="'${icoarray[$i]}'">'${exearray[$i]}'</Program>'; 
      fi
done
echo '</Menu>';
fi

## System Menu
if [[ "$csys" = "yes" ]]; then
echo '<Menu label="'${catarraylc[10]}'" icon="'${icoarraylc[10]}'">';
for i in "${!apparray[@]}"; do
      # Skip MX tools
      if is_mx_tool "${apparray[$i]}"; then
          continue
      fi
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"System"* && "$Categories" != *"Modul"* || "$Categories" == *"Settings"* && "$Categories" != *"Modul"* ]]; then
         echo '<Program label="'${namarray[$i]}'" icon="'${icoarray[$i]}'">'${exearray[$i]}'</Program>'; 
      fi
done
echo '</Menu>';
fi

## Preferences Menu
if [[ "$cpre" = "yes" ]]; then
echo '<Menu label="'${catarraylc[11]}'" icon="'${icoarraylc[11]}'">';
for i in "${!apparray[@]}"; do
      # Skip MX tools
      if is_mx_tool "${apparray[$i]}"; then
          continue
      fi
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"System"* && "$Categories" != *"Modul"* || "$Categories" == *"Settings"* && "$Categories" != *"Modul"* ]]; then
         echo '<Program label="'${namarray[$i]}'" icon="'${icoarray[$i]}'">'${exearray[$i]}'</Program>'; 
      fi
done
echo '</Menu>';
fi

## Modules Menu
if [[ "$cmod" = "yes" ]]; then
echo '<Menu label="'$namemod'" icon="'$icomod'">';
for i in "${!apparray[@]}"; do
      # Skip MX tools
      if is_mx_tool "${apparray[$i]}"; then
          continue
      fi
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"Modul"* ]]; then
         echo '<Program label="'${namarray[$i]}'" icon="'${icoarray[$i]}'">'${exearray[$i]}'</Program>'; 
      fi
done
echo '</Menu>';
fi

## Science Menu
if [[ "$csci" = "yes" ]]; then
echo '<Menu label="'${catarraylc[12]}'" icon="'${icoarraylc[12]}'">';
for i in "${!apparray[@]}"; do
      # Skip MX tools
      if is_mx_tool "${apparray[$i]}"; then
          continue
      fi
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"Science"* && "$Categories" != *"System"* ]]; then
         echo '<Program label="'${namarray[$i]}'" icon="'${icoarray[$i]}'">'${exearray[$i]}'</Program>'; 
      fi
done
echo '</Menu>';
fi

## Universal Menu
if [[ "$cuni" = "yes" ]]; then
echo '<Menu label="'${catarraylc[13]}'" icon="'${icoarraylc[13]}'">';
for i in "${!apparray[@]}"; do
      # Skip MX tools
      if is_mx_tool "${apparray[$i]}"; then
          continue
      fi
      Categories=${catarray[$i]};
      if [[ "$Categories" == *"Universal"* && "$Categories" != *"System"* ]]; then
         echo '<Program label="'${namarray[$i]}'" icon="'${icoarray[$i]}'">'${exearray[$i]}'</Program>'; 
      fi
done
echo '</Menu>';
fi

## XML footer
unset apparray;
unset catarray;
unset namarray;
unset icoarray;
unset exearray;
unset catarraylc;
unset icoarraylc;
unset mxtools_array;
unset IFS;
echo '</JWM>';
